// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RocketRMM.Data;

#nullable disable

namespace RocketRMM.Data.Migrations.UserProfilesDbContext_Migrations
{
    [DbContext(typeof(UserProfilesDbContext))]
    [Migration("20231030223545_InitialCreate_UserProfilesDbContext")]
    partial class InitialCreate_UserProfilesDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RocketRMM.Data.UserProfile", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("identityProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("_userProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
